# Generated by Django 5.1.5 on 2025-01-25 12:05

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_user_groups_alter_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbook",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="textbook_images/"
            ),
        ),
    ]
