# Generated by Django 5.1.7 on 2025-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0005_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="subject",
            field=models.CharField(default="Placeholder", max_length=255),
            preserve_default=False,
        ),
    ]
